# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio2face.proto
"""Generated protocol buffer code."""
from modules.MLinking.protobuf.google.protobuf.internal import builder as _builder
from modules.MLinking.protobuf.google.protobuf import descriptor as _descriptor
from modules.MLinking.protobuf.google.protobuf import descriptor_pool as _descriptor_pool
from modules.MLinking.protobuf.google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61udio2face.proto\x12\x08tutorial\",\n\x07Request\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x10\n\x08tts_type\x18\x02 \x01(\t\"`\n\x08Response\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0f\n\x07\x65motion\x18\x02 \x01(\x02\x12\x10\n\x08\x62s_value\x18\x03 \x03(\x02\x12\x0e\n\x06\x62s_key\x18\x04 \x03(\t\x12\x10\n\x08wav_data\x18\x05 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio2face_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=30
  _REQUEST._serialized_end=74
  _RESPONSE._serialized_start=76
  _RESPONSE._serialized_end=172
# @@protoc_insertion_point(module_scope)
